const fertilizerDB = {
  rice:        { name:'Urea + DAP',       npkRatio:'20-10-10', quantity:'120 kg/acre',       timing:'Split: 50% basal, 25% tillering, 25% panicle', notes:'Avoid excess N to prevent lodging' },
  wheat:       { name:'NPK 12-32-16',     npkRatio:'12-32-16', quantity:'100 kg/acre',       timing:'Full dose at sowing',                           notes:'Apply Zinc sulfate 25 kg/acre if deficient' },
  maize:       { name:'Urea + SSP + MOP', npkRatio:'25-12-12', quantity:'130 kg/acre',       timing:'Half N basal, half N at knee-high stage',       notes:'Micronutrient mixture beneficial' },
  chickpea:    { name:'DAP + MOP',        npkRatio:'5-20-20',  quantity:'50 kg/acre',        timing:'Full basal dose at sowing',                     notes:'Legume — Rhizobium inoculation recommended' },
  kidneybeans: { name:'SSP + MOP',        npkRatio:'5-25-25',  quantity:'60 kg/acre',        timing:'Full basal at sowing',                          notes:'Over-fertilizing with N reduces yield' },
  pigeonpeas:  { name:'SSP + MOP',        npkRatio:'5-20-20',  quantity:'50 kg/acre',        timing:'Basal application',                             notes:'Nitrogen fixation reduces fertilizer need' },
  mothbeans:   { name:'SSP',              npkRatio:'5-15-5',   quantity:'30 kg/acre',        timing:'At sowing',                                     notes:'Drought-tolerant; minimal inputs needed' },
  mungbean:    { name:'DAP',              npkRatio:'5-20-15',  quantity:'40 kg/acre',        timing:'Basal dose',                                    notes:'Seed inoculation with Rhizobium for best results' },
  blackgram:   { name:'DAP',              npkRatio:'5-20-15',  quantity:'40 kg/acre',        timing:'Basal dose',                                    notes:'Responds well to phosphorus application' },
  lentil:      { name:'SSP + MOP',        npkRatio:'5-25-20',  quantity:'45 kg/acre',        timing:'Full basal',                                    notes:'Seed treatment with Rhizobium culture' },
  pomegranate: { name:'NPK 10-26-26',     npkRatio:'10-26-26', quantity:'2 kg/plant/yr',     timing:'Split in 3 doses annually',                    notes:'Foliar spray of micronutrients beneficial' },
  banana:      { name:'Urea + MOP',       npkRatio:'18-8-46',  quantity:'200 g/plant/month', timing:'Monthly fertigation',                           notes:'Potassium critical for bunch development' },
  mango:       { name:'NPK 12-12-17',     npkRatio:'12-12-17', quantity:'2 kg/tree/yr',      timing:'Pre-flowering and post-harvest',                notes:'Avoid N during flower initiation' },
  grapes:      { name:'NPK 13-0-46',      npkRatio:'13-0-46',  quantity:'Per vine/yr',       timing:'Fertigation schedule',                          notes:'Potassium important for fruit quality' },
  watermelon:  { name:'NPK 15-15-15',     npkRatio:'15-15-15', quantity:'80 kg/acre',        timing:'Basal + topdress at vine development',          notes:'Calcium spray prevents blossom end rot' },
  muskmelon:   { name:'NPK 15-15-15',     npkRatio:'15-15-15', quantity:'70 kg/acre',        timing:'Basal + topdress',                              notes:'Reduce N at fruit set to improve sweetness' },
  apple:       { name:'NPK 12-32-16',     npkRatio:'12-32-16', quantity:'3 kg/tree/yr',      timing:'Pre-bloom application',                         notes:'Calcium and boron sprays for fruit quality' },
  orange:      { name:'Urea + SSP + MOP', npkRatio:'15-10-10', quantity:'2 kg/tree/yr',      timing:'Split in 3 doses',                              notes:'Magnesium deficiency common — apply MgSO4' },
  papaya:      { name:'NPK 13-0-46',      npkRatio:'13-0-46',  quantity:'100 g/plant/month', timing:'Monthly',                                       notes:'Avoid waterlogging for fertilizer efficiency' },
  coconut:     { name:'NPK 12-12-17',     npkRatio:'12-12-17', quantity:'1 kg/palm',         timing:'Twice annually (June and December)',             notes:'Responds well to organic manure' },
  cotton:      { name:'Urea + DAP + MOP', npkRatio:'24-12-12', quantity:'150 kg/acre',       timing:'1/3 basal, 2/3 split at squaring and boll',     notes:'Boron spray at flowering improves boll set' },
  jute:        { name:'Urea + SSP',       npkRatio:'20-10-5',  quantity:'80 kg/acre',        timing:'Half at sowing, half 30 days after',            notes:'Potassium improves fibre quality' },
  coffee:      { name:'NPK 17-17-17',     npkRatio:'17-17-17', quantity:'200 g/plant',       timing:'4 splits annually',                             notes:'Shade-grown coffee needs less fertilizer' },
  sugarcane:   { name:'Urea + SSP + MOP', npkRatio:'25-12-12', quantity:'180 kg/acre',       timing:'1/3 basal, 1/3 at 30 days, 1/3 at 60 days',    notes:'Potassium improves sugar content and stalk strength' },
  mustard:     { name:'DAP + MOP',        npkRatio:'12-32-16', quantity:'75 kg/acre',         timing:'Full basal dose at sowing',                     notes:'Sulfur application (20 kg/acre) boosts oil content' },
  barley:      { name:'NPK 12-32-16',     npkRatio:'12-32-16', quantity:'80 kg/acre',         timing:'Full dose at sowing',                           notes:'Avoid excess nitrogen — reduces grain quality' },
};

module.exports = fertilizerDB;
